# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/noureldinhendy/Developmentspace/ECE30862-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/noureldinhendy/Developmentspace/ECE30862-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/noureldinhendy/Developmentspace/ECE30862-project/CMakeFiles /Users/noureldinhendy/Developmentspace/ECE30862-project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/noureldinhendy/Developmentspace/ECE30862-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ECE30862_project

# Build rule for target.
ECE30862_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ECE30862_project
.PHONY : ECE30862_project

# fast build rule for target.
ECE30862_project/fast:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/build
.PHONY : ECE30862_project/fast

src/ConditionFactory.o: src/ConditionFactory.cpp.o

.PHONY : src/ConditionFactory.o

# target to build an object file
src/ConditionFactory.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/ConditionFactory.cpp.o
.PHONY : src/ConditionFactory.cpp.o

src/ConditionFactory.i: src/ConditionFactory.cpp.i

.PHONY : src/ConditionFactory.i

# target to preprocess a source file
src/ConditionFactory.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/ConditionFactory.cpp.i
.PHONY : src/ConditionFactory.cpp.i

src/ConditionFactory.s: src/ConditionFactory.cpp.s

.PHONY : src/ConditionFactory.s

# target to generate assembly for a file
src/ConditionFactory.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/ConditionFactory.cpp.s
.PHONY : src/ConditionFactory.cpp.s

src/GameObjectModel.o: src/GameObjectModel.cpp.o

.PHONY : src/GameObjectModel.o

# target to build an object file
src/GameObjectModel.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/GameObjectModel.cpp.o
.PHONY : src/GameObjectModel.cpp.o

src/GameObjectModel.i: src/GameObjectModel.cpp.i

.PHONY : src/GameObjectModel.i

# target to preprocess a source file
src/GameObjectModel.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/GameObjectModel.cpp.i
.PHONY : src/GameObjectModel.cpp.i

src/GameObjectModel.s: src/GameObjectModel.cpp.s

.PHONY : src/GameObjectModel.s

# target to generate assembly for a file
src/GameObjectModel.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/GameObjectModel.cpp.s
.PHONY : src/GameObjectModel.cpp.s

src/GameWorld.o: src/GameWorld.cpp.o

.PHONY : src/GameWorld.o

# target to build an object file
src/GameWorld.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/GameWorld.cpp.o
.PHONY : src/GameWorld.cpp.o

src/GameWorld.i: src/GameWorld.cpp.i

.PHONY : src/GameWorld.i

# target to preprocess a source file
src/GameWorld.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/GameWorld.cpp.i
.PHONY : src/GameWorld.cpp.i

src/GameWorld.s: src/GameWorld.cpp.s

.PHONY : src/GameWorld.s

# target to generate assembly for a file
src/GameWorld.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/GameWorld.cpp.s
.PHONY : src/GameWorld.cpp.s

src/HasCondition.o: src/HasCondition.cpp.o

.PHONY : src/HasCondition.o

# target to build an object file
src/HasCondition.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/HasCondition.cpp.o
.PHONY : src/HasCondition.cpp.o

src/HasCondition.i: src/HasCondition.cpp.i

.PHONY : src/HasCondition.i

# target to preprocess a source file
src/HasCondition.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/HasCondition.cpp.i
.PHONY : src/HasCondition.cpp.i

src/HasCondition.s: src/HasCondition.cpp.s

.PHONY : src/HasCondition.s

# target to generate assembly for a file
src/HasCondition.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/HasCondition.cpp.s
.PHONY : src/HasCondition.cpp.s

src/Item.o: src/Item.cpp.o

.PHONY : src/Item.o

# target to build an object file
src/Item.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Item.cpp.o
.PHONY : src/Item.cpp.o

src/Item.i: src/Item.cpp.i

.PHONY : src/Item.i

# target to preprocess a source file
src/Item.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Item.cpp.i
.PHONY : src/Item.cpp.i

src/Item.s: src/Item.cpp.s

.PHONY : src/Item.s

# target to generate assembly for a file
src/Item.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Item.cpp.s
.PHONY : src/Item.cpp.s

src/Room.o: src/Room.cpp.o

.PHONY : src/Room.o

# target to build an object file
src/Room.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Room.cpp.o
.PHONY : src/Room.cpp.o

src/Room.i: src/Room.cpp.i

.PHONY : src/Room.i

# target to preprocess a source file
src/Room.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Room.cpp.i
.PHONY : src/Room.cpp.i

src/Room.s: src/Room.cpp.s

.PHONY : src/Room.s

# target to generate assembly for a file
src/Room.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Room.cpp.s
.PHONY : src/Room.cpp.s

src/StatusCondition.o: src/StatusCondition.cpp.o

.PHONY : src/StatusCondition.o

# target to build an object file
src/StatusCondition.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/StatusCondition.cpp.o
.PHONY : src/StatusCondition.cpp.o

src/StatusCondition.i: src/StatusCondition.cpp.i

.PHONY : src/StatusCondition.i

# target to preprocess a source file
src/StatusCondition.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/StatusCondition.cpp.i
.PHONY : src/StatusCondition.cpp.i

src/StatusCondition.s: src/StatusCondition.cpp.s

.PHONY : src/StatusCondition.s

# target to generate assembly for a file
src/StatusCondition.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/StatusCondition.cpp.s
.PHONY : src/StatusCondition.cpp.s

src/Trigger.o: src/Trigger.cpp.o

.PHONY : src/Trigger.o

# target to build an object file
src/Trigger.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Trigger.cpp.o
.PHONY : src/Trigger.cpp.o

src/Trigger.i: src/Trigger.cpp.i

.PHONY : src/Trigger.i

# target to preprocess a source file
src/Trigger.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Trigger.cpp.i
.PHONY : src/Trigger.cpp.i

src/Trigger.s: src/Trigger.cpp.s

.PHONY : src/Trigger.s

# target to generate assembly for a file
src/Trigger.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/Trigger.cpp.s
.PHONY : src/Trigger.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ECE30862_project.dir/build.make CMakeFiles/ECE30862_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ECE30862_project"
	@echo "... src/ConditionFactory.o"
	@echo "... src/ConditionFactory.i"
	@echo "... src/ConditionFactory.s"
	@echo "... src/GameObjectModel.o"
	@echo "... src/GameObjectModel.i"
	@echo "... src/GameObjectModel.s"
	@echo "... src/GameWorld.o"
	@echo "... src/GameWorld.i"
	@echo "... src/GameWorld.s"
	@echo "... src/HasCondition.o"
	@echo "... src/HasCondition.i"
	@echo "... src/HasCondition.s"
	@echo "... src/Item.o"
	@echo "... src/Item.i"
	@echo "... src/Item.s"
	@echo "... src/Room.o"
	@echo "... src/Room.i"
	@echo "... src/Room.s"
	@echo "... src/StatusCondition.o"
	@echo "... src/StatusCondition.i"
	@echo "... src/StatusCondition.s"
	@echo "... src/Trigger.o"
	@echo "... src/Trigger.i"
	@echo "... src/Trigger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

